"""empty message

Revision ID: 2b8d20600c93
Revises: 7a539afa5ffd
Create Date: 2022-03-15 14:06:17.317952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8d20600c93'
down_revision = '7a539afa5ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('demand_name', sa.Text(), nullable=False),
    sa.Column('demand_href', sa.String(length=200), nullable=False),
    sa.Column('pm_name', sa.Text(), nullable=True),
    sa.Column('rd_name', sa.Text(), nullable=True),
    sa.Column('test_name', sa.Text(), nullable=True),
    sa.Column('isDelete', sa.Integer(), nullable=True),
    sa.Column('test_time', sa.DateTime(), nullable=True),
    sa.Column('online_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand')
    # ### end Alembic commands ###
