"""empty message

Revision ID: 398f9c1a0b6e
Revises: 4a7a7a650118
Create Date: 2022-02-24 14:58:30.042430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398f9c1a0b6e'
down_revision = '4a7a7a650118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('modular', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'modular')
    # ### end Alembic commands ###
