"""empty message

Revision ID: 4a7a7a650118
Revises: b8a4c62a6da2
Create Date: 2022-02-24 13:50:06.625549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7a7a650118'
down_revision = 'b8a4c62a6da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('request_method', sa.String(length=29), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'request_method')
    # ### end Alembic commands ###
