"""empty message

Revision ID: 7a539afa5ffd
Revises: 03b47f869334
Create Date: 2022-03-10 10:51:14.403831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a539afa5ffd'
down_revision = '03b47f869334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'update_time')
    # ### end Alembic commands ###
