"""empty message

Revision ID: 9253a9b5376a
Revises: c59c56867576
Create Date: 2022-03-03 15:18:43.797579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9253a9b5376a'
down_revision = 'c59c56867576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
