"""empty message

Revision ID: 96f26e956f51
Revises: 2b8d20600c93
Create Date: 2022-03-15 14:11:26.811197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f26e956f51'
down_revision = '2b8d20600c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand', 'status')
    # ### end Alembic commands ###
